security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
    # Role hierarchy configuration
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$hMmMQVQR.Mie0vj99qGZD.V7QCOGXdrNyOWsLuZxXFEiKIrGZ3Xge
                        roles:
                            - ROLE_ADMIN
                    chiheb.hadjamor@datapowa.fr:
                        password: $2y$13$hn9P8MPHS/Gsv5O7w3SDxOWXxp0DgzB55ODd.aghewZPEN0ftpYsW
                        roles:
                            - ROLE_ADMIN
        app_user_provider:
            id: security.user.provider.entity.user
        # Chain provider to use both in-memory and database users
        all_users:
            chain:
                providers: ['users_in_memory', 'app_user_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: username
                password_parameter: _password
                enable_csrf: true
                default_target_path: app_accounts
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: false
            logout:
                path: app_logout
                target: app_login
    access_control:
        -
            path: ^/login
            roles: PUBLIC_ACCESS
        -
            path: ^/verify-2fa
            roles: IS_AUTHENTICATED_REMEMBERED
        -
            path: ^/
            roles: ROLE_USER
